sudo: required
services: 
  - docker

before_install:
  - docker build -t impluto/docker-react-tests -f Dockerfile.dev .

script:
  - docker run -e CI=true impluto/docker-react-tests npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-250115516148"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY